### ISSUE TITLE
Spans Question

### ISSUE THREAD

**Issue by nataliaElv** [argilla-io/roadmap#19]
### Summary
_Summarize the functionality or added value of the feature:_

A new question for the Feedback Datasets, where it is possible to draw spans to highlight fragments of text while applying a label.

### User needs
_Set out the problem to be solved and the preferences or needs of users:_

- Respond to Token Classification and Text Classification tasks within the same dataset.
- Add a comment section to a Token Classification task.
- Most of the time, we want to select full tokens, but for some types of data it is also important to have the possibility to annotate by character.

### Proposed solution
_Outline the initial solution to the problems or needs of the user:_

- Add a Spans question to Feedback Datasets.
- Support the possibility to annotate full tokens but also by character.

### Further context
_Add any additional information or details needed to understand the feature:_

```[tasklist]
### Related issues
- [ ] https://github.com/argilla-io/argilla/issues/1868
- [ ] https://github.com/argilla-io/argilla/issues/1947
- [ ] https://github.com/argilla-io/argilla/issues/1871
- [ ] https://github.com/argilla-io/argilla/issues/2353
- [ ] https://github.com/argilla-io/argilla/issues/2279
- [ ] https://github.com/argilla-io/argilla/issues/1852
```

**Comment by vmehta-cohere** [comment]
Awesome! Would love to see this come to fruition

**Comment by nataliaElv** [comment]
@vmehta-cohere We've added the new `SpanQuestion` in Feedback datasets in version 1.26.0, so you can already try this out! The overlapping spans should come in the next release 😄 Let us know how it goes!
