### ISSUE TITLE
View metadata at the record level

### ISSUE THREAD

**Issue by Amelie-V** [argilla-io/roadmap#30]
### Summary
_Summarize the functionality or added value of the feature:_

Visualize the metadata of each specific record.

### User needs
_Set out the problem to be solved and the preferences or needs of users:_

- See the metadata applied to a specific record.
- Some users might want to see it at first level, others are happy with the modal from other dataset types.

### Proposed solution
_Outline the initial solution to the problems or needs of the user:_

- Provide a way to visualize metadata at the record level.

### Further context
_Add any additional information or details needed to understand the feature:_

**Comment by davidberenstein1957** [comment]
+ one from GSK
