### ISSUE TITLE
Progress overview by dataset

### ISSUE THREAD

**Issue by Amelie-V** [argilla-io/roadmap#33]
First version: **global annotation progress**

Provide to the owner/admin an overview of the annotation progress by status (submitted, pending, draft, discarded).
This overview should be visible before entering in the dataset view (related to the redesign of the datasets list)

Future version: **cross visibility for an annotation team**
https://github.com/argilla-io/argilla/issues/3882

**Comment by davidberenstein1957** [comment]
According to GSK it would also be useful as an annotator to see an overview of the used record labels and potential label overlap to assess the progress of the annotation task. This could for example be a barchart with the distribution of the assigned labels. This is also something we've seen within datamaran workflows.
