### ISSUE TITLE
Weak supervision based annotations for multimodal models

### ISSUE THREAD

**Issue by pikaduck** [argilla-io/roadmap#74]
I have been checking out Rubrix for a lot of tasks. But we see that the new VisionTransformer based multimodal Los are gaining momentum & giving great results on tasks such as NER & QA. I would like to know if Rubrix has support for weak supervision based annotation of data for multimodal models, especially for the task of NER, wherein we found the FUNSD dataset format the optimum to get started with. If this is not a feature yet, I would request the maintainers of the project to release this as well soon since there are very less open source tools that are good enough for these dataset formats.

**Comment by frascuchon** [comment]
Refs #26
